# Generated by Django 3.1 on 2021-01-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210126_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Singredient',
            new_name='Ingredient',
        ),
    ]
