# Generated by Django 3.1 on 2021-01-22 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210122_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
