# Generated by Django 3.1.5 on 2021-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_ingredient_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
    ]
